name: docker
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      REPO: monstrenyatko/wireguard-client
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        run: |
          ./build.sh "$REPO:$(date +%Y-%m-%d)" "--push"
          ./build.sh "$REPO:latest" "--push"
